
[base]
runtime = "20s"
tls_ca = ".certs/ca.crt"
tls_cert = ".certs/client.crt"
tls_key = ".certs/client.key"

[matrix]
#frequency = [ 1, 2, 10 ]
frequency = [ 10 ]
message_len = 32

[[matrix.clients]]
publishers = 10
subscribers = 200


[[drivers]]
mode = "mqtt"
container = "ghcr.io/ryankurte/dsf-iot-eval/iot-perf-mqtt"
port = 1883

[[drivers]]
mode = "mqtts"
container = "ghcr.io/ryankurte/dsf-iot-eval/iot-perf-mqtt"
port = 8883

[[drivers]]
mode = "coap"
container = "ghcr.io/ryankurte/dsf-iot-eval/iot-perf-coap"
command = "coap-server --endpoints 1000"
port = 5683

[[drivers]]
mode = "coaps"
container = "ghcr.io/ryankurte/dsf-iot-eval/iot-perf-coap"
command = "coap-server --endpoints 1000 --port 5684 --dtls"
port = 5684

[[drivers]]
mode = "dsf"
#container = "ghcr.io/ryankurte/dsf-iot-eval/iot-perf-dsf"
container = "ghcr.io/dist-svc/dsf"
port = 10100
env = [
#    "DSF_DB_FILE=/run/dsfd.db",
    "DSF_DB_FILE=sqlite://:memory:?cache=shared",
    "DSF_SOCK=/var/dsfd.sock",
    "LOG_LEVEL=warn",
]
